version: '3.2'
services:
    app:
        build: .
        ports:
            - "5000:5000"
        environment:
            - FLASK_DEBUG=1
        env_file:
            - secrets.env
        volumes:
            - .:/usr/src/app